version: "3.8"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Portugal
    ports:
      - 1880:1880
    networks:
      - idc-net
    volumes:
      - ./data/node-red-data:/data

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./data/mosquitto-data/config:/mosquitto/config
      - ./data/mosquitto-data/data:/mosquitto/data
      - ./data/mosquitto-data/log:/mosquitto/log
    networks:
      - idc-net

  web:
    build: ./data/app-data/
    container_name: app
    ports:
      - 8000:8000
    networks:
      - idc-net
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data/db-data:/var/lib/mysql
    networks:
      - idc-net

networks:
  idc-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.10.0/24